server:
  port: 8081
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
    max-swallow-size: -1
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/s053?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filter:
        wall:
          config:
            multi-statement-allow: true
    hikari:
      max-lifetime: 60000
      maximum-pool-size: 1000